import { z } from "zod";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "../_core/trpc";
import { getCustomerAddress, getOperationsSummary, listCustomerAddresses, listDiscountCodes, listShippingZones, quoteLocalProductOrder, removeCustomerAddress, removeDiscountCode, removeShippingZone, saveCustomerAddress, saveDiscountCode, saveShippingZone } from "../localCommerce";

const addressSchema = z.object({ label: z.string().trim().min(1).max(80), recipientName: z.string().trim().min(2).max(160), phone: z.string().trim().min(7).max(32), country: z.string().trim().min(2).max(96), city: z.string().trim().min(2).max(96), address: z.string().trim().min(5).max(2000), isDefault: z.boolean().default(false) });
const shippingSchema = z.object({ city: z.string().trim().min(2).max(96), label: z.string().trim().min(2).max(160), amount: z.coerce.number().min(0).max(10_000_000), currencyCode: z.string().trim().length(3).default("EGP"), estimatedDays: z.string().trim().min(2).max(80), isActive: z.boolean().default(true) });
const discountSchema = z.object({ code: z.string().trim().min(3).max(64).regex(/^[A-Za-z0-9_-]+$/, "استخدم أحرفًا إنجليزية وأرقامًا وشرطة أو شرطة سفلية فقط."), discountType: z.enum(["نسبة", "مبلغ ثابت"]), value: z.coerce.number().positive().max(10_000_000), minimumAmount: z.coerce.number().min(0).max(10_000_000).default(0), maxUses: z.coerce.number().int().min(0).max(10_000_000).default(0), isActive: z.boolean().default(true), expiresAt: z.coerce.date().optional().nullable() });
const quoteSchema = z.object({ productId: z.number().int().positive(), city: z.string().trim().min(2).max(96), quantity: z.number().int().min(1).max(100).default(1), couponCode: z.string().trim().max(64).optional() });

export const storeBasicsRouter = router({
  addresses: router({
    mine: protectedProcedure.query(({ ctx }) => listCustomerAddresses(ctx.user.id)),
    get: protectedProcedure.input(z.object({ addressId: z.number().int().positive() })).query(({ ctx, input }) => getCustomerAddress(ctx.user.id, input.addressId)),
    save: protectedProcedure.input(addressSchema.extend({ addressId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const { addressId, isDefault, ...values } = input; const id = await saveCustomerAddress(ctx.user.id, { ...values, isDefault: isDefault ? 1 : 0 }, addressId); return { id }; }),
    remove: protectedProcedure.input(z.object({ addressId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await removeCustomerAddress(ctx.user.id, input.addressId); return { success: true } as const; }),
  }),
  shipping: router({ publicZones: publicProcedure.query(() => listShippingZones(true)), quote: publicProcedure.input(quoteSchema).query(({ input }) => quoteLocalProductOrder(input)), adminList: adminProcedure.query(() => listShippingZones(false)), save: adminProcedure.input(shippingSchema.extend({ zoneId: z.number().int().positive().optional() })).mutation(async ({ input }) => { const { zoneId, amount, isActive, currencyCode, ...values } = input; await saveShippingZone({ ...values, amount: amount.toFixed(2), currencyCode: currencyCode.toUpperCase(), isActive: isActive ? 1 : 0 }, zoneId); return { success: true } as const; }), remove: adminProcedure.input(z.object({ zoneId: z.number().int().positive() })).mutation(async ({ input }) => { await removeShippingZone(input.zoneId); return { success: true } as const; }) }),
  discounts: router({ adminList: adminProcedure.query(() => listDiscountCodes()), save: adminProcedure.input(discountSchema.extend({ discountId: z.number().int().positive().optional() })).mutation(async ({ input }) => { const { discountId, value, minimumAmount, isActive, code, ...values } = input; await saveDiscountCode({ ...values, code: code.toUpperCase(), value: value.toFixed(2), minimumAmount: minimumAmount.toFixed(2), isActive: isActive ? 1 : 0 }, discountId); return { success: true } as const; }), remove: adminProcedure.input(z.object({ discountId: z.number().int().positive() })).mutation(async ({ input }) => { await removeDiscountCode(input.discountId); return { success: true } as const; }) }),
  operations: adminProcedure.query(() => getOperationsSummary()),
});
