import { StoreLayout } from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ClipboardList, LoaderCircle, PackageCheck, UserRound } from "lucide-react";

export default function Account() {
  const { user, loading } = useAuth();
  if (loading) return <StoreLayout><div className="container grid min-h-[60vh] place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-[#b76f2c]" /></div></StoreLayout>;
  if (!user) return <StoreLayout><div className="container grid min-h-[65vh] place-items-center py-12"><div className="max-w-lg rounded-[32px] border border-stone-200 bg-white p-8 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#e3eee8] text-[#173c37]"><UserRound className="h-7 w-7" /></span><h1 className="mt-5 text-3xl font-black text-[#173c37]">حسابك في سوقك العربي</h1><p className="mt-3 leading-7 text-stone-600">سجّل الدخول للاطلاع على سجل طلباتك وحالة كل طلب بعد اكتمال ربط حسابات العملاء.</p><Button onClick={() => startLogin()} className="mt-7 h-12 rounded-xl bg-[#173c37] px-7 font-extrabold hover:bg-[#0f2b27]">تسجيل الدخول</Button></div></div></StoreLayout>;
  const { data: orders = [], isLoading: ordersLoading } = trpc.orders.mine.useQuery();
  return <StoreLayout><div className="container py-12"><div className="rounded-[32px] bg-[#173c37] p-7 text-white sm:p-10"><p className="text-sm text-[#f5c96a]">مرحبًا بك</p><h1 className="mt-2 text-3xl font-black">{user.name || "عميل سوقك العربي"}</h1><p className="mt-3 text-sm text-stone-300">{user.email || ""}</p></div><section className="mt-8 rounded-3xl border border-stone-200 bg-white p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e3eee8] text-[#173c37]"><ClipboardList className="h-5 w-5" /></span><div><h2 className="text-xl font-black text-[#173c37]">سجل الطلبات</h2><p className="text-sm text-stone-500">تابع حالة كل طلب من هنا.</p></div></div>{ordersLoading ? <div className="grid min-h-40 place-items-center"><LoaderCircle className="h-5 w-5 animate-spin text-[#b76f2c]" /></div> : orders.length ? <div className="mt-7 overflow-x-auto"><table className="w-full min-w-[640px] text-right text-sm"><thead className="border-b border-stone-200 text-stone-500"><tr><th className="pb-3 font-bold">رقم الطلب</th><th className="pb-3 font-bold">التاريخ</th><th className="pb-3 font-bold">الدفع</th><th className="pb-3 font-bold">الإجمالي</th><th className="pb-3 font-bold">الحالة</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} className="border-b border-stone-100"><td className="py-4 font-extrabold text-[#173c37]">{order.orderNumber}</td><td className="py-4 text-stone-600">{new Date(order.createdAt).toLocaleDateString("ar-EG")}</td><td className="py-4 text-stone-600">{order.paymentMethod}</td><td className="py-4 font-bold text-[#173c37]">{Number(order.total).toLocaleString("ar-EG")} {order.currencyCode}</td><td className="py-4"><span className="rounded-full bg-[#e3eee8] px-3 py-1 text-xs font-bold text-[#173c37]">{order.status}</span></td></tr>)}</tbody></table></div> : <div className="mt-7 rounded-2xl border border-dashed border-stone-300 bg-[#fffdf8] px-6 py-12 text-center"><PackageCheck className="mx-auto h-8 w-8 text-[#b76f2c]" /><h3 className="mt-4 font-extrabold text-[#173c37]">لا توجد طلبات مرتبطة بالحساب بعد</h3><p className="mx-auto mt-2 max-w-md text-sm leading-7 text-stone-500">ستظهر هنا الحالات: معلق، مؤكد، مشحون، مكتمل.</p></div>}</section></div></StoreLayout>;
}
