import { FavoriteButton } from "@/components/FavoriteButton";
import { StoreLayout } from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BookMarked, BookOpenText, CheckCircle2, LibraryBig, LockKeyhole, Search, Sparkles } from "lucide-react";
import { Link } from "wouter";

const assets = { anime: "/manus-storage/anime-detective-library_b2e046e6.jpg", holmesDoor: "/manus-storage/sherlock-holmes-door_99f48e75.jpg", holmesPortrait: "/manus-storage/sherlock-holmes-portrait_ce4cd534.jpg" };
const journey = [{ icon: Search, step: "01", title: "اكتشف كتابك", text: "ابحث في المكتبة أو تصفح المختارات الرقمية." }, { icon: CheckCircle2, step: "02", title: "أكمل السداد", text: "اختر وسيلة الدفع وارفع إثبات السداد من حسابك." }, { icon: BookMarked, step: "03", title: "اقرأ متى شئت", text: "يُمنح الكتاب بعد المراجعة وتحفظ المكتبة موضع قراءتك." }];

function FeaturedBookSkeletons() {
  return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3" aria-label="جارٍ تحميل الكتب" aria-busy="true">{Array.from({ length: 3 }, (_, index) => <div key={index} className="animate-pulse rounded-3xl border border-[#ded9ed] bg-white p-6"><div className="h-20 w-14 rounded-xl bg-[#ebe8f5]" /><div className="mt-8 h-3 w-20 rounded bg-[#f2efe9]" /><div className="mt-3 h-6 w-4/5 rounded bg-[#ebe8f5]" /><div className="mt-4 h-3 w-full rounded bg-[#f2efe9]" /><div className="mt-2 h-3 w-4/5 rounded bg-[#f2efe9]" /><div className="mt-7 h-10 border-t border-stone-100" /></div>)}</div>;
}

export default function Home() {
  const { data: books = [], isLoading } = trpc.digitalBooks.catalog.useQuery();
  return <StoreLayout>
    <section className="relative isolate overflow-hidden bg-[#101a22] text-white"><div className="absolute inset-0 opacity-25"><img src={assets.anime} alt="قارئ في أجواء غامضة" className="h-full w-full object-cover object-center" /></div><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_15%,rgba(193,144,81,.44),transparent_30%),linear-gradient(90deg,rgba(16,26,34,.98)_0%,rgba(16,26,34,.91)_42%,rgba(16,26,34,.42)_100%)]" /><div className="container relative grid min-h-[560px] items-center gap-10 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><p className="flex items-center gap-2 text-xs font-extrabold tracking-[0.2em] text-[#f5c96a]"><span className="h-px w-8 bg-[#f5c96a]" />مكتبة عربية</p><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.12] sm:text-6xl lg:text-7xl">كل حكاية تبدأ<br /><span className="text-[#f5c96a]">بصفحة واحدة.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-stone-200 sm:text-lg">اكتشف الكتب الورقية والرقمية والمنتجات، واختر ما تريد من مكان واحد.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-xl bg-[#f5c96a] px-6 font-extrabold text-[#173c37] hover:bg-[#edbd53]"><Link href="/المنتجات">اختر ما تريد <ArrowLeft className="mr-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-12 rounded-xl border-white/30 bg-white/5 px-6 text-white hover:bg-white/10 hover:text-white"><Link href="/كتب-رقمية"><LibraryBig className="ml-2 h-4 w-4" />الكتب الرقمية</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-stone-300"><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-[#f5c96a]" />وصول محمي بعد اعتماد السداد</span><span className="flex items-center gap-2"><BookOpenText className="h-4 w-4 text-[#f5c96a]" />قارئ PDF يحفظ تقدمك</span></div></div><div className="hidden justify-self-end lg:block"><div className="relative w-[360px] rounded-[32px] border border-white/10 bg-white/5 p-4 backdrop-blur-sm"><div className="absolute -right-4 -top-4 rounded-full bg-[#f5c96a] px-4 py-2 text-xs font-black text-[#173c37]">كتب · منتجات · اختيارات</div><img src={assets.anime} alt="أجواء غموض وقراءة" className="aspect-square w-full rounded-[24px] object-cover" /><div className="absolute bottom-8 right-8 left-8 rounded-2xl bg-[#101a22]/90 p-4 backdrop-blur"><p className="text-xs font-bold text-[#f5c96a]">اكتشف ما يناسبك</p><p className="mt-1 text-lg font-black">اختر ما تريد من مكان واحد</p></div></div></div></div></section>
    <section className="border-b border-stone-200 bg-[#fffdf8]"><div className="container grid gap-4 py-6 sm:grid-cols-3">{journey.map(item => { const Icon = item.icon; return <div key={item.step} className="flex gap-3 border-stone-200 sm:border-l sm:pl-4 last:border-0"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8e4f5] text-[#50427b]"><Icon className="h-5 w-5" /></span><div><p className="text-[10px] font-black tracking-[.14em] text-[#b76f2c]">{item.step}</p><h2 className="mt-0.5 font-black text-[#173c37]">{item.title}</h2><p className="mt-1 text-xs leading-5 text-stone-500">{item.text}</p></div></div>; })}</div></section>
    <section className="container py-16"><div className="mb-9 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold tracking-[0.18em] text-[#b76f2c]">المكتبة الرقمية</p><h2 className="mt-2 text-3xl font-black text-[#173c37]">ابدأ من كتاب يثير فضولك</h2><p className="mt-3 max-w-xl leading-7 text-stone-600">استخدم البحث والفلاتر داخل المكتبة للوصول إلى الكتاب الذي تريده بسرعة.</p></div><Button asChild variant="outline" className="w-fit rounded-xl border-[#173c37] text-[#173c37] hover:bg-[#173c37] hover:text-white"><Link href="/كتب-رقمية">عرض كل الكتب <ArrowLeft className="mr-2 h-4 w-4" /></Link></Button></div>{isLoading ? <FeaturedBookSkeletons /> : books.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{books.slice(0, 6).map((book, index) => <article key={book.id} className="group relative overflow-hidden rounded-3xl border border-[#ded9ed] bg-white p-6 shadow-[0_12px_30px_rgba(80,66,123,.06)]"><div className={`absolute inset-x-0 top-0 h-1.5 ${index % 2 ? "bg-[#b76f2c]" : "bg-[#50427b]"}`} /><div className="flex items-start justify-between gap-3">{book.coverUrl ? <img src={book.coverUrl} alt={`غلاف ${book.title}`} className="h-20 w-14 rounded-xl object-cover shadow-sm" /> : <span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#ebe8f5] text-[#50427b]"><BookOpenText className="h-6 w-6" /></span>}<FavoriteButton compact item={{ itemType: "كتاب رقمي", itemId: book.id, title: book.title, subtitle: book.description, price: book.price, currencyCode: book.currencyCode, imageUrl: book.coverUrl, targetPath: `/كتب-رقمية/${book.productHandle}` }} /></div><p className="mt-8 text-xs font-bold tracking-[.14em] text-[#b76f2c]">{book.category || "كتاب رقمي"}</p><h3 className="mt-2 text-xl font-black text-[#173c37]">{book.title}</h3><p className="mt-3 min-h-14 text-sm leading-7 text-stone-600">{book.description || "كتاب متاح للشراء والقراءة داخل مكتبتك بعد اعتماد السداد."}</p><div className="mt-6 flex items-center justify-between border-t border-stone-100 pt-5"><strong className="text-base text-[#50427b]">{Number(book.price).toLocaleString("ar-EG")} {book.currencyCode}</strong><Link href={`/كتب-رقمية/${book.productHandle}`} className="text-sm font-black text-[#173c37] transition-transform group-hover:-translate-x-1">اكتشف الكتاب <ArrowLeft className="mr-1 inline h-4 w-4" /></Link></div></article>)}</div> : <div className="rounded-3xl border border-dashed border-[#cfc8e7] bg-[#faf9ff] px-6 py-14 text-center"><BookOpenText className="mx-auto h-9 w-9 text-[#50427b]" /><h3 className="mt-4 text-xl font-black text-[#173c37]">مكتبتك الجديدة تبدأ من هنا</h3><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-stone-500">أضف أول كتاب وملف PDF من بوابة المدير ليظهر في هذه الواجهة.</p><Button asChild className="mt-6 rounded-xl bg-[#50427b] hover:bg-[#42355f]"><Link href="/كتب-رقمية">فتح المكتبة الرقمية</Link></Button></div>}</section>
    <section className="overflow-hidden bg-[#efeae0]"><div className="container grid items-stretch gap-8 py-16 lg:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-[420px] overflow-hidden rounded-[32px] bg-[#1a2930]"><img src={assets.holmesDoor} alt="أجواء تحقيق كلاسيكية" className="absolute inset-0 h-full w-full object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-t from-[#101a22] via-[#101a22]/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white"><p className="text-xs font-bold tracking-[.18em] text-[#f5c96a]">زوايا المكتبة</p><h2 className="mt-2 text-3xl font-black">لأن كل لغز<br />يحتاج قارئًا صبورًا.</h2></div></div><div className="flex flex-col justify-center"><p className="text-xs font-extrabold tracking-[0.18em] text-[#b76f2c]">تحقيقات وقراءة</p><h2 className="mt-3 max-w-2xl text-4xl font-black leading-tight text-[#173c37]">من الرواية البوليسية إلى الحكاية التي لا تُنسى.</h2><p className="mt-5 max-w-2xl leading-8 text-stone-600">اختر كتابًا، أكمل السداد بالطريقة التي تناسبك، ثم تابع القراءة من حسابك دون أن تفقد موضعك.</p><div className="mt-7 grid gap-4 sm:grid-cols-[150px_1fr]"><img src={assets.holmesPortrait} alt="بورتريه أدبي كلاسيكي" className="h-44 w-full rounded-2xl object-cover object-top" /><div className="rounded-2xl border border-[#d5cbb9] bg-[#fffdf8] p-5"><Sparkles className="h-5 w-5 text-[#b76f2c]" /><h3 className="mt-3 font-black text-[#173c37]">قراءة مملوكة لك</h3><p className="mt-2 text-sm leading-7 text-stone-600">بعد اعتماد السداد، تجد كتبك في المكتبة الرقمية، مع خيارات القراءة والتنزيل المرخص.</p><Button asChild variant="link" className="mt-2 h-auto p-0 text-[#173c37]"><Link href="/مكتبتي">اذهب إلى مكتبتي <ArrowLeft className="mr-1 h-4 w-4" /></Link></Button></div></div></div></div></section>
  </StoreLayout>;
}
