import { StoreLayout } from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { ArrowLeft, FileCheck2, LockKeyhole, RotateCcw, Truck } from "lucide-react";
import { Link, useLocation } from "wouter";

const policies = {
  "/سياسة-الشحن": { icon: Truck, eyebrow: "توصيل واضح", title: "سياسة الشحن", intro: "تعرض تكلفة الشحن المتاحة قبل تسجيل الطلب بحسب المدينة التي تختارها. إذا لم تكن المدينة مهيأة بعد، يظهر تنبيه بأن تفاصيل الشحن ستؤكد بعد مراجعة الطلب.", sections: [["كيف تُحسب التكلفة؟", "تكلفة الشحن تأتي من إعدادات المدينة في المتجر، ولا تُعتمد من نص يكتبه العميل. يظهر ملخص المنتجات والخصم والشحن والإجمالي قبل التسجيل."], ["متى يبدأ التنفيذ؟", "تبدأ معالجة الطلب بعد مراجعة إثبات السداد. تظهر حالة الطلب في «طلباتي» باعتبارها: معلق، مؤكد، مشحون، أو مكتمل."], ["تعديل العنوان", "يمكنك اختيار عنوان محفوظ أو إدخال عنوان جديد قبل تسجيل الطلب. إذا احتجت تعديلًا بعد التسجيل، تواصل عبر واتساب وأرسل مرجع الطلب."]], action: "عرض طلباتي", path: "/طلباتي" },
  "/الاستبدال-والاسترجاع": { icon: RotateCcw, eyebrow: "خدمة ما بعد البيع", title: "سياسة الاستبدال والاسترجاع", intro: "طلبات الاستبدال أو الاسترجاع تُراجع بحسب حالة المنتج وبيانات الطلب. احتفظ دائمًا بمرجع الطلب وصورة إثبات السداد عند التواصل.", sections: [["قبل طلب المراجعة", "تأكد من أن المنتج لم يُستخدم، واحتفظ بالتغليف وما يثبت حالة المنتج عند الاستلام. أرسل رقم الطلب وسبب الطلب بوضوح."], ["المنتجات الرقمية", "الكتب الرقمية تُمنح للعميل بعد اعتماد الدفع وتمكين الوصول، ولذلك تختلف طبيعتها عن المنتجات المادية. راجع وصف الكتاب والسعر قبل تسجيل الطلب."], ["كيف تتواصل؟", "افتح طلباتك أولًا ثم تواصل عبر واتساب مع تضمين مرجع الطلب، ليسهل على المدير التحقق من الحالة وتقديم الإجراء المناسب."]], action: "التواصل عبر واتساب", path: "https://wa.me/201146303129" },
  "/الخصوصية": { icon: LockKeyhole, eyebrow: "بياناتك محفوظة", title: "سياسة الخصوصية", intro: "يستخدم المتجر بيانات الحساب والتواصل والعنوان اللازمة لتسجيل الطلب ومتابعة الدفع والتنفيذ. لا ينبغي إرسال بيانات دفع حساسة داخل حقول الملاحظات أو واتساب.", sections: [["ما الذي يُحفظ؟", "يحفظ المتجر بيانات الطلب، وسيلة الدفع المختارة، حالة التنفيذ، وإثبات السداد الذي ترفعه لمراجعة عملية الدفع. كما تحفظ العناوين التي تختار حفظها ضمن حسابك."], ["الغرض من البيانات", "تُستخدم البيانات لمتابعة الطلب، التحقق من السداد، منح الكتب الرقمية بعد الاعتماد، والتواصل المرتبط بخدمة الطلب."], ["التحكم في الحساب", "يمكنك حذف عناوينك المحفوظة من حسابك عند توفر إدارة العناوين، ولا تعني إزالة العنوان حذف البيانات التي يلزم الاحتفاظ بها ضمن طلب مسجل سابقًا."]], action: "العودة إلى المتجر", path: "/بحث" },
} as const;

export default function StorePolicy() {
  const [location] = useLocation(); const policy = policies[location as keyof typeof policies] ?? policies["/سياسة-الشحن"]; const Icon = policy.icon; const external = policy.path.startsWith("http");
  return <StoreLayout><section className="border-b border-stone-200 bg-[linear-gradient(135deg,#e3eee8,#fffdf8)]"><div className="container py-12"><p className="text-xs font-extrabold tracking-[0.18em] text-[#2d7a51]">{policy.eyebrow}</p><h1 className="mt-2 text-4xl font-black text-[#173c37]">{policy.title}</h1><p className="mt-4 max-w-3xl leading-8 text-stone-600">{policy.intro}</p></div></section><main className="container max-w-4xl py-10"><div className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e3eee8] text-[#173c37]"><Icon className="h-6 w-6" /></span><div className="mt-6 space-y-6">{policy.sections.map(([title, text]) => <section key={title} className="border-b border-stone-100 pb-6 last:border-0 last:pb-0"><h2 className="text-xl font-black text-[#173c37]">{title}</h2><p className="mt-3 leading-8 text-stone-600">{text}</p></section>)}</div><Button asChild className="mt-8 rounded-xl bg-[#173c37]">{external ? <a href={policy.path} target="_blank" rel="noreferrer">{policy.action}<ArrowLeft className="mr-2 h-4 w-4" /></a> : <Link href={policy.path}>{policy.action}<ArrowLeft className="mr-2 h-4 w-4" /></Link>}</Button></div><p className="mt-5 flex items-center gap-2 text-xs leading-6 text-stone-500"><FileCheck2 className="h-4 w-4 text-[#2d7a51]" />تُراجع أي تفاصيل تشغيلية خاصة بطلبك من صفحة «طلباتي» وبيانات الدفع المعروضة مع الطلب.</p></main></StoreLayout>;
}
