import { and, desc, eq, gte, sql } from "drizzle-orm";
import { customerAddresses, discountCodes, localProducts, orderItems, orders, paymentMethods, shippingZones } from "../drizzle/schema";
import { getDb } from "./db";

export type CustomerAddressInput = { label: string; recipientName: string; phone: string; country: string; city: string; address: string; isDefault: number };
export type ShippingZoneInput = { city: string; label: string; amount: string; currencyCode: string; estimatedDays: string; isActive: number };
export type DiscountCodeInput = { code: string; discountType: "نسبة" | "مبلغ ثابت"; value: string; minimumAmount: string; maxUses: number; isActive: number; expiresAt?: Date | null };

export async function listCustomerAddresses(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(customerAddresses).where(eq(customerAddresses.userId, userId)).orderBy(desc(customerAddresses.isDefault), desc(customerAddresses.updatedAt)); }
export async function getCustomerAddress(userId: number, addressId: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(customerAddresses).where(and(eq(customerAddresses.userId, userId), eq(customerAddresses.id, addressId))).limit(1))[0]; }
export async function saveCustomerAddress(userId: number, input: CustomerAddressInput, addressId?: number) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا.");
  return db.transaction(async tx => { if (input.isDefault) await tx.update(customerAddresses).set({ isDefault: 0 }).where(eq(customerAddresses.userId, userId)); if (addressId) { await tx.update(customerAddresses).set(input).where(and(eq(customerAddresses.id, addressId), eq(customerAddresses.userId, userId))); return addressId; } const inserted = await tx.insert(customerAddresses).values({ userId, ...input }); return Number(inserted[0].insertId); });
}
export async function removeCustomerAddress(userId: number, addressId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); await db.delete(customerAddresses).where(and(eq(customerAddresses.userId, userId), eq(customerAddresses.id, addressId))); }

export async function listShippingZones(onlyActive = false) { const db = await getDb(); if (!db) return []; return onlyActive ? db.select().from(shippingZones).where(eq(shippingZones.isActive, 1)).orderBy(shippingZones.city) : db.select().from(shippingZones).orderBy(shippingZones.city); }
export async function saveShippingZone(input: ShippingZoneInput, zoneId?: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); if (zoneId) await db.update(shippingZones).set(input).where(eq(shippingZones.id, zoneId)); else await db.insert(shippingZones).values(input); }
export async function removeShippingZone(zoneId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); await db.delete(shippingZones).where(eq(shippingZones.id, zoneId)); }

export async function listDiscountCodes() { const db = await getDb(); if (!db) return []; return db.select().from(discountCodes).orderBy(desc(discountCodes.createdAt)); }
export async function saveDiscountCode(input: DiscountCodeInput, discountId?: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); if (discountId) await db.update(discountCodes).set(input).where(eq(discountCodes.id, discountId)); else await db.insert(discountCodes).values(input); }
export async function removeDiscountCode(discountId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); await db.delete(discountCodes).where(eq(discountCodes.id, discountId)); }

type PricingInput = { productId: number; city: string; quantity: number; couponCode?: string };
async function calculatePricing(tx: any, input: PricingInput) {
  const product = (await tx.select().from(localProducts).where(eq(localProducts.id, input.productId)).limit(1))[0];
  if (!product || !product.isAvailable || product.inventory < input.quantity) throw new Error("هذا المنتج غير متاح بالكمية المطلوبة حاليًا.");
  const shipping = (await tx.select().from(shippingZones).where(and(eq(shippingZones.city, input.city), eq(shippingZones.isActive, 1))).limit(1))[0] ?? null;
  if (shipping && shipping.currencyCode !== product.currencyCode) throw new Error("عملة الشحن لهذه المدينة لا تطابق عملة المنتج.");
  const subtotal = Number(product.price) * input.quantity; let coupon: typeof discountCodes.$inferSelect | null = null; let discountAmount = 0;
  const code = input.couponCode?.trim().toUpperCase();
  if (code) { coupon = (await tx.select().from(discountCodes).where(eq(discountCodes.code, code)).limit(1))[0] ?? null; if (!coupon || !coupon.isActive) throw new Error("كوبون الخصم غير متاح."); if (coupon.expiresAt && coupon.expiresAt.getTime() < Date.now()) throw new Error("انتهت صلاحية كوبون الخصم."); if (coupon.maxUses > 0 && coupon.usedCount >= coupon.maxUses) throw new Error("تم استخدام كوبون الخصم للحد الأقصى."); if (subtotal < Number(coupon.minimumAmount)) throw new Error(`يتطلب الكوبون حدًا أدنى قدره ${Number(coupon.minimumAmount).toFixed(2)} ${product.currencyCode}.`); discountAmount = coupon.discountType === "نسبة" ? subtotal * (Number(coupon.value) / 100) : Number(coupon.value); discountAmount = Math.min(subtotal, discountAmount); }
  const shippingAmount = shipping ? Number(shipping.amount) : 0; const total = Math.max(0, subtotal - discountAmount + shippingAmount);
  return { product, shipping, coupon, subtotal, discountAmount, shippingAmount, total };
}
export async function quoteLocalProductOrder(input: PricingInput) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا."); return db.transaction(async tx => { const pricing = await calculatePricing(tx, input); return { subtotal: pricing.subtotal.toFixed(2), discountAmount: pricing.discountAmount.toFixed(2), shippingAmount: pricing.shippingAmount.toFixed(2), total: pricing.total.toFixed(2), currencyCode: pricing.product.currencyCode, shippingLabel: pricing.shipping?.label ?? "شحن يُحدّد عند تأكيد الطلب", estimatedDays: pricing.shipping?.estimatedDays ?? "سيؤكد المدير تكلفة وموعد الشحن بعد مراجعة الطلب", couponCode: pricing.coupon?.code ?? null }; }); }

export async function createEnhancedLocalProductOrder(input: { productId: number; userId: number; customerName: string; customerPhone: string; shippingAddress: string; country: string; city: string; quantity: number; couponCode?: string; paymentMethod: (typeof paymentMethods)[number] }) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حاليًا.");
  return db.transaction(async tx => { const pricing = await calculatePricing(tx, input); const suffix = `${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2, 6).toUpperCase()}`; const orderNumber = `LP-${suffix}`; const paymentReference = `PAY-${suffix}`; const inserted = await tx.insert(orders).values({ orderNumber, userId: input.userId, sourceCartId: `local-product-${pricing.product.id}-${suffix}`, customerName: input.customerName, customerPhone: input.customerPhone, shippingAddress: input.shippingAddress, country: input.country, city: input.city, paymentMethod: input.paymentMethod, total: pricing.total.toFixed(2), subtotal: pricing.subtotal.toFixed(2), discountAmount: pricing.discountAmount.toFixed(2), shippingAmount: pricing.shippingAmount.toFixed(2), couponCode: pricing.coupon?.code ?? null, currencyCode: pricing.product.currencyCode, paymentReference, checkoutUrl: "" }); const orderId = Number(inserted[0].insertId); await tx.insert(orderItems).values({ orderId, variantId: `local-product-${pricing.product.id}`, productHandle: pricing.product.handle, productTitle: pricing.product.title, variantTitle: pricing.product.category, imageUrl: pricing.product.imageUrl, unitPrice: Number(pricing.product.price).toFixed(2), quantity: input.quantity, lineTotal: pricing.subtotal.toFixed(2) }); const stock = await tx.update(localProducts).set({ inventory: pricing.product.inventory - input.quantity }).where(and(eq(localProducts.id, pricing.product.id), gte(localProducts.inventory, input.quantity))); if (!stock[0].affectedRows) throw new Error("نفد مخزون المنتج أثناء تسجيل الطلب. حدّث الصفحة وحاول مجددًا."); if (pricing.coupon) { const update = await tx.update(discountCodes).set({ usedCount: sql`${discountCodes.usedCount} + 1` }).where(sql`${discountCodes.id} = ${pricing.coupon.id} AND (${discountCodes.maxUses} = 0 OR ${discountCodes.usedCount} < ${discountCodes.maxUses})`); if (!update[0].affectedRows) throw new Error("تم استخدام الكوبون للحد الأقصى. حدّث الصفحة وحاول مجددًا."); } return { orderId, orderNumber, paymentReference, total: pricing.total.toFixed(2), subtotal: pricing.subtotal.toFixed(2), discountAmount: pricing.discountAmount.toFixed(2), shippingAmount: pricing.shippingAmount.toFixed(2), currencyCode: pricing.product.currencyCode }; });
}

export async function getOperationsSummary() { const db = await getDb(); if (!db) return { orders: 0, pending: 0, completed: 0, revenue: "0.00", lowStock: [] as (typeof localProducts.$inferSelect)[] }; const [allOrders, products] = await Promise.all([db.select().from(orders), db.select().from(localProducts)]); const revenue = allOrders.filter(order => order.paymentStatus === "مدفوع" || order.status === "مكتمل").reduce((sum, order) => sum + Number(order.total), 0); return { orders: allOrders.length, pending: allOrders.filter(order => order.status === "معلق").length, completed: allOrders.filter(order => order.status === "مكتمل").length, revenue: revenue.toFixed(2), lowStock: products.filter(product => product.inventory <= 5).sort((a, b) => a.inventory - b.inventory).slice(0, 8) }; }
