import { auditDigitalBooks } from "@/lib/storeQuality";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, FileSearch, LoaderCircle, RefreshCw, SearchCheck, ShieldCheck } from "lucide-react";
import { useMemo } from "react";
import { Button } from "./ui/button";

export function StoreQualityGuard() {
  const auditQuery = trpc.digitalBooks.adminList.useQuery();
  const audit = useMemo(() => auditDigitalBooks(auditQuery.data ?? []), [auditQuery.data]);
  const tone = audit.criticalCount ? "bg-rose-50 text-rose-800" : audit.warningCount ? "bg-amber-50 text-amber-800" : "bg-[#eaf3ee] text-[#205f39]";

  return <section id="quality-guard" className="mt-7 scroll-mt-24 overflow-hidden rounded-3xl border border-[#cfe0d9] bg-white shadow-[0_12px_30px_rgba(23,60,55,0.05)]">
    <div className="flex flex-col gap-4 border-b border-[#dbe9e2] bg-[#f4faf6] p-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#173c37] text-[#f5c96a]"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-xs font-bold tracking-[.14em] text-[#2d7a51]">فحص تلقائي مجاني</p><h2 className="mt-1 text-xl font-black text-[#173c37]">حارس جودة المتجر وSEO</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">يفحص الكتب الموجودة عند فتح لوحة الإدارة ويعرض ما يحتاجه العرض والبحث. لا يستخدم AI ولا يرسل بياناتك إلى أي خدمة خارجية.</p></div></div><Button type="button" variant="outline" onClick={() => auditQuery.refetch()} disabled={auditQuery.isFetching} className="shrink-0 rounded-xl border-[#173c37] text-[#173c37]"><RefreshCw className={`ml-2 h-4 w-4 ${auditQuery.isFetching ? "animate-spin" : ""}`} />إعادة الفحص</Button></div>
    {auditQuery.isLoading ? <div className="grid min-h-44 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-[#173c37]" /></div> : auditQuery.error ? <div className="p-6 text-sm text-rose-700">تعذر تحميل بيانات الفحص الآن. حدّث الصفحة ثم حاول مرة أخرى.</div> : <div className="p-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<SearchCheck className="h-4 w-4" />} label="درجة الجاهزية" value={`${audit.score}/100`} tone={tone} /><Metric icon={<FileSearch className="h-4 w-4" />} label="كتب متاحة" value={String(audit.liveBooks)} tone="bg-[#ebe8f5] text-[#50427b]" /><Metric icon={<AlertTriangle className="h-4 w-4" />} label="تحذيرات" value={String(audit.warningCount)} tone="bg-amber-50 text-amber-800" /><Metric icon={<AlertTriangle className="h-4 w-4" />} label="مشكلات حرجة" value={String(audit.criticalCount)} tone="bg-rose-50 text-rose-800" /></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-[#eaf3ee] px-3 py-2 text-[#205f39]">robots.txt مفعّل</span><span className="rounded-full bg-[#eaf3ee] px-3 py-2 text-[#205f39]">sitemap.xml مفعّل</span><span className="rounded-full bg-[#f7ead6] px-3 py-2 text-[#744819]">لا يضمن الفحص ترتيبًا أو فهرسة فورية من Google</span></div>{audit.issues.length ? <div className="mt-6 space-y-3"><h3 className="font-black text-[#173c37]">أولويات التحسين</h3>{audit.issues.slice(0, 8).map(issue => <article key={`${issue.bookId}-${issue.title}`} className={`rounded-2xl border p-4 ${issue.severity === "critical" ? "border-rose-200 bg-rose-50" : "border-amber-200 bg-amber-50"}`}><div className="flex items-start gap-3"><AlertTriangle className={`mt-0.5 h-4 w-4 shrink-0 ${issue.severity === "critical" ? "text-rose-700" : "text-amber-700"}`} /><div><p className="font-extrabold text-[#173c37]">{issue.title} <span className="font-normal text-stone-500">— {issue.bookTitle}</span></p><p className="mt-1 text-sm leading-6 text-stone-600">{issue.detail}</p></div></div></article>)}</div> : <div className="mt-6 flex items-start gap-3 rounded-2xl bg-[#eaf3ee] p-5 text-[#205f39]"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0" /><div><h3 className="font-black">الكتب الحالية مكتملة وفق معايير الحارس</h3><p className="mt-1 text-sm leading-6">ما زال تحسين المحتوى الأصلي والتسويق الخارجي مهمًا، لكن لا توجد بيانات كتاب ناقصة يكتشفها الفحص الآن.</p></div></div>}</div>}
  </section>;
}

function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) {
  return <div className={`rounded-2xl p-4 ${tone}`}><span className="flex items-center gap-2 text-xs font-bold opacity-80">{icon}{label}</span><strong className="mt-3 block text-2xl font-black">{value}</strong></div>;
}
